// data.js — Contenido de las 10 estaciones del museo (5 nacionales + 5 internacionales)
// Fichas sustentadas en fuentes verificadas: MinTIC, SENA, Fundacion Escuela Nueva,
// Ministerio de Educacion de Finlandia, High Tech High, Exploratorium, MOE Singapur y NPDL (Michael Fullan)
const STATIONS = {
  n1: { zona:'nac', img:'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
    categoria:'Urbano',
    nombre:'1. Computadores para Educar - Aulas del Siglo XXI',
    contexto:'Programa social del Gobierno de Colombia, liderado por MinTIC, MEN, Presidencia y el SENA. En sus más de 20 años de operación ha entregado más de 2,2 millones de equipos a cerca de 43.000 sedes educativas públicas, reduciendo la relación de estudiantes por computador de 24 a 4 entre 2010 y 2018.',
    enfoque:'Cierre de la brecha digital como condición de equidad educativa, combinando dotación tecnológica con apropiación pedagógica.',
    metodologia:'Formación docente en uso pedagógico de TIC mediante diplomados, talleres y los encuentros nacionales "Educa Digital".',
    tics:'Computadores y tabletas reacondicionados, laboratorios de innovación y Kits Maker de robótica fabricados con partes recicladas.',
    aportes:'Su Centro Nacional de Aprovechamiento de Residuos Electrónicos (CENARE) en Bogotá es la única planta estatal de este tipo en América Latina, y el programa ha evitado la deserción de cerca de 162.000 estudiantes.' },
  n2: { zona:'nac', img:'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800',
    categoria:'Rural',
    nombre:'2. Escuela Nueva - Modelo de Vicky Colbert',
    contexto:'Modelo pedagógico colombiano creado en los años setenta por la socióloga Vicky Colbert junto a Óscar Mogollón y Beryl Levinger, diseñado para escuelas rurales multigrado con un solo docente para varios grados. Colbert recibió por este trabajo el Premio WISE 2013, considerado el "Nobel de la educación".',
    enfoque:'Aprendizaje centrado en el estudiante, con espíritu democrático que involucra a docentes, alumnos y familias en la toma de decisiones, inspirado en Dewey y Montessori.',
    metodologia:'Guías de Aprendizaje autoinstructivas que combinan libro de texto, cuaderno de trabajo y guía docente, permitiendo que cada niño avance a su propio ritmo con apoyo de compañeros más avanzados.',
    tics:'Materiales impresos estructurados como tecnología educativa base, hoy complementados con plataformas digitales de seguimiento en zonas con conectividad.',
    aportes:'El modelo se aplica hoy en cerca de 20.000 escuelas colombianas y se ha extendido a 19 países, incluidos Brasil, Filipinas e India.' },
  n3: { zona:'nac', img:'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=800',
    categoria:'Media Técnica',
    nombre:'3. Tecnoacademias SENA - Ruta STEM',
    contexto:'Programa del Servicio Nacional de Aprendizaje (SENA) que articula la educación media técnica con laboratorios de investigación, ciencia, tecnología e innovación (I+D+i) dirigidos a jóvenes en formación complementaria.',
    enfoque:'Vocación temprana hacia carreras STEM (ciencia, tecnología, ingeniería y matemáticas) mediante la resolución de problemáticas reales del entorno productivo regional.',
    metodologia:'Aprendizaje Basado en Proyectos y Retos, con acompañamiento de instructores SENA y articulación con el sector productivo local.',
    tics:'Laboratorios de electrónica, programación, robótica, impresión 3D y simulación de procesos industriales.',
    aportes:'Fortalece el tránsito de estudiantes de educación media hacia programas técnicos y tecnológicos, acercando la formación para el trabajo a comunidades con menor oferta universitaria.' },
  n4: { zona:'nac', img:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
    categoria:'Posconflicto',
    nombre:'4. Diplomado Rural TIC - Educación para la Paz',
    contexto:'Estrategia de Computadores para Educar desarrollada en 60 municipios de 15 departamentos, dirigida a territorios priorizados en procesos de reconciliación y posconflicto.',
    enfoque:'Educación para la paz y la convivencia mediante metodologías innovadoras y competencias socioemocionales aplicadas al aula.',
    metodologia:'Formación de docentes y directivos rurales en actividades pedagógicas orientadas a la reconciliación, combinadas con el uso de tecnologías digitales en el aula.',
    tics:'Plataformas de formación docente y contenidos digitales adaptados a las condiciones de conectividad de las zonas rurales dispersas.',
    aportes:'Busca capacitar a cerca de 2.500 docentes y directivos, integrando la reconstrucción del tejido social como eje transversal del currículo escolar.' },
  n5: { zona:'nac', img:'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
    categoria:'Étnico-Intercultural',
    nombre:'5. Fomento a la Educación con Tecnología - Territorios Diversos',
    contexto:'Estrategia vigente de Computadores para Educar dirigida a gobernaciones y alcaldías, que amplía la dotación tecnológica y fortalece los procesos de enseñanza en instituciones educativas públicas de todo el país, incluidos territorios étnicos e interculturales.',
    enfoque:'Cofinanciación entre la Nación y las Entidades Territoriales para sostener la transformación digital educativa de manera articulada con las particularidades culturales locales.',
    metodologia:'Esquemas de inversión conjunta con gobernaciones y alcaldías, acompañados de procesos de formación docente para un uso pedagógico sostenible.',
    tics:'Dotación de equipos de cómputo, laboratorios de innovación y contenidos digitales adaptables a distintos contextos culturales y lingüísticos.',
    aportes:'Se articula con la convocatoria nacional "Tecnologías para Aprender", buscando consolidar la tecnología como herramienta clave de transformación educativa en 2025 y años siguientes.' },
  i1: { zona:'intl', img:'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=800',
    categoria:'Sistema Nacional',
    nombre:'6. Aprendizaje Basado en Fenómenos — Finlandia',
    contexto:'Reforma curricular nacional finlandesa vigente desde agosto de 2016, que introdujo el "Phenomenon-Based Learning" (aprendizaje basado en fenómenos) como política pública obligatoria en todas las escuelas del país para estudiantes de 7 a 16 años.',
    enfoque:'Abordaje interdisciplinario de fenómenos de la vida real (como el cambio climático o la Unión Europea) en lugar de asignaturas fragmentadas, desarrollando comunicación, colaboración, creatividad y pensamiento crítico.',
    metodologia:'Los estudiantes investigan en equipo un fenómeno de interés real, con docentes que codiseñan y coenseñan de forma interdisciplinaria, y participan en la evaluación de lo aprendido.',
    tics:'Entornos personales de aprendizaje digital utilizados como herramienta para obtener, procesar y construir conocimiento durante la investigación del fenómeno.',
    aportes:'Antes de la implementación nacional, cerca del 70% de los docentes finlandeses fueron formados en esta perspectiva, y ciudades como Helsinki establecieron un mínimo de dos fenómenos de estudio por año escolar.' },
  i2: { zona:'intl', img:'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800',
    categoria:'Red Charter',
    nombre:'7. High Tech High — San Diego, Estados Unidos',
    contexto:'Red de escuelas públicas charter fundada en el año 2000 en San Diego, California, reconocida internacionalmente como referente del "Deeper Learning" (aprendizaje profundo).',
    enfoque:'Integración de rigor académico, equidad y aprendizaje aplicado, eliminando el rastreo académico (tracking) y priorizando la diversidad estudiantil en cada aula.',
    metodologia:'Aprendizaje Basado en Proyectos interdisciplinario, donde cada proyecto culmina en una exhibición pública del trabajo ante la comunidad, reemplazando en gran medida los exámenes estandarizados.',
    tics:'Herramientas de diseño digital, documentación audiovisual de procesos y plataformas colaborativas para la construcción de portafolios estudiantiles.',
    aportes:'Su modelo ha influido en el diseño de escuelas de proyecto en distintos países y es ampliamente estudiado como referente de evaluación auténtica basada en evidencias de trabajo real.' },
  i3: { zona:'intl', img:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    categoria:'Aprendizaje No Formal',
    nombre:'8. Tinkering Studio — Exploratorium de San Francisco',
    contexto:'Laboratorio de aprendizaje del museo de ciencias Exploratorium en San Francisco, pionero mundial del movimiento "maker" aplicado a la educación informal.',
    enfoque:'Construccionismo: el conocimiento se construye haciendo, experimentando y iterando, en lugar de recibirlo de forma pasiva.',
    metodologia:'"Tinkering" o experimentación exploratoria guiada, donde el error se entiende como parte natural e iterativa del proceso creativo, combinando arte, ciencia e ingeniería.',
    tics:'Microcontroladores de hardware libre como Arduino, kits de electrónica accesible y herramientas de prototipado rápido.',
    aportes:'Ha influido en la creación de espacios "maker" y "fab labs" educativos alrededor del mundo, reformulando la relación entre error y aprendizaje en entornos escolares y museísticos.' },
  i4: { zona:'intl', img:'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    categoria:'Política Nacional',
    nombre:'9. Smart Nation e IT Masterplan — Singapur',
    contexto:'Política educativa nacional impulsada por el Ministerio de Educación de Singapur dentro de la iniciativa "Smart Nation", que ha desarrollado sucesivos Masterplan de TIC en educación desde los años noventa.',
    enfoque:'Desarrollo del pensamiento computacional y la autorregulación del aprendizaje mediante entornos digitales altamente estructurados y basados en evidencia.',
    metodologia:'Progresión pedagógica Concreto-Pictórico-Abstracto (CPA), ampliamente usada en la enseñanza de matemáticas del "Método Singapur", adoptado hoy en decenas de países.',
    tics:'Plataformas de aprendizaje adaptativo y analíticas de datos educativos que permiten ajustar la enseñanza al progreso individual de cada estudiante.',
    aportes:'Singapur ocupa consistentemente los primeros lugares en las pruebas internacionales PISA y TIMSS, siendo referente global en articulación entre política pública y tecnología educativa.' },
  i5: { zona:'intl', img:'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    categoria:'Red Global',
    nombre:'10. New Pedagogies for Deep Learning (NPDL) — Michael Fullan',
    contexto:'Red internacional de escuelas e investigadores educativos liderada por el académico canadiense Michael Fullan, que reúne instituciones de más de una decena de países en torno al aprendizaje profundo.',
    enfoque:'Marco de las "6 Cs" — Character (carácter), Citizenship (ciudadanía), Collaboration (colaboración), Communication (comunicación), Creativity (creatividad) y Critical Thinking (pensamiento crítico) — que integra el aprendizaje académico con el bienestar socioemocional.',
    metodologia:'Diseño de experiencias de aprendizaje que conectan a los estudiantes con problemas reales del mundo, evaluando su progreso mediante rúbricas específicas para cada una de las 6 Cs.',
    tics:'Plataformas globales de intercambio entre escuelas participantes, videoconferencia y herramientas colaborativas en la nube para compartir evidencias de aprendizaje.',
    aportes:'Fullan sostiene que integrar el aprendizaje académico con las competencias socioemocionales en un solo paradigma facilita sistemas educativos más inclusivos y efectivos a gran escala.' }
};
