const STATIONS = {
n1: { zona:'nac', nombre:'1. Redes y Gamificacion, hacia una nueva evaluacion',
img:'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800',
contexto:'Institucion Educativa Rancheria, Sahagun (entorno urbano-rural, grado 10). Surge como respuesta al rezago academico postpandemia y a las dificultades en Trigonometria y Fisica, buscando recuperar aprendizajes y motivacion.',
enfoque:'Constructivista (aprendizaje significativo mediante resolucion de problemas reales), socioconstructivista (trabajo en equipo y liderazgo mediante el rol de capitan) y por competencias (aplicar el conocimiento, no memorizarlo).',
metodologia:'Gamificacion mediante juegos de roles (Piratas del Caribe, Piratas de Rancheria) con retos y objetivos; Aprendizaje Basado en Problemas; aprendizaje colaborativo con roles definidos; y aprendizaje experiencial con practicas de campo e informes.',
tics:'GeoGebra para explicar funciones trigonometricas de forma visual; TikTok y Kwai para evaluacion creativa mediante videos.',
aportes:'Evaluacion mas alla del examen escrito (juegos, videos, trabajo en equipo); integracion de redes sociales al aprendizaje; fortalecimiento de habilidades blandas (liderazgo, comunicacion); respuesta directa a brechas de aprendizaje post pandemia.' },
n2: { zona:'nac', nombre:'2. Mi Escuela Canta',
img:'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
contexto:'Institucion Educativa Nuestra Senora de Belen, Cucuta, con estudiantes de estratos 1 y 2 desde preescolar hasta secundaria. Busca ofrecer experiencias significativas, fortalecer la salud mental y abrir espacios de expresion artistica libre.',
enfoque:'Humanista (desarrollo integral y expresion emocional), socioconstructivista (interaccion entre estudiantes, docentes y familias), inclusivo (respeto y participacion de todos) y transversal (la musica como eje articulador de multiples areas).',
metodologia:'Aprendizaje Basado en Proyectos continuo, donde cada cancion es un eje tematico; aprendizaje experiencial mediante canto, baile y reflexion; aprendizaje colaborativo con familias; y educacion artistica como estrategia didactica.',
tics:'WhatsApp para compartir letras de canciones y comunicacion educativa; YouTube para difundir los videos musicales del proyecto.',
aportes:'El arte como eje pedagogico central; fortalecimiento socioemocional y de la salud mental escolar; vinculacion activa de la familia; produccion de canciones ineditas del docente lider; aprendizaje significativo y transversal.' },
n3: { zona:'nac', nombre:'3. Edupuntos.co, donde aprender es ganar dos veces',
img:'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800',
contexto:'Institucion Educativa Juan B. Caballero, Villavicencio, desde transicion hasta grado 11. Surge de la necesidad de integrar educacion academica, etica y financiera junto con ambientes virtuales de aprendizaje.',
enfoque:'Por competencias (habilidades cognitivas, sociales y financieras), constructivista (autonomia mediante interaccion con la plataforma), transversal (integra grados y asignaturas) y bilingue (actividades en ingles y espanol).',
metodologia:'Aprendizaje en entornos virtuales mediante una plataforma digital central; gamificacion con un sistema de bonificacion (Edupuntos); aprendizaje autonomo donde el estudiante elige sus actividades; y retos con distintos niveles de complejidad.',
tics:'Plataforma virtual tipo CMS, sistema de comercio educativo y plugins complementarios para gestionar contenidos y seguir el progreso del estudiante.',
aportes:'Plataforma integral que une lo academico, etico, financiero y ciudadano; economia educativa que simula recompensas reales; aprendizaje personalizado por ritmo; proyeccion internacional en el Inter-National Teacher Development Programme (Reino Unido, 2018).' },
n4: { zona:'nac', nombre:'4. Tratamiento Automatizado de Residuos Organicos Domiciliarios',
img:'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=800',
contexto:'Institucion Educativa Cadena Las Playas, Santiago de Cali, con 4 sedes y cerca de 1.200 estudiantes, ademas de 2.000 estudiantes tecnicos del programa CASD. La Jornada Unica y el restaurante escolar generan altos volumenes de residuos organicos.',
enfoque:'Por competencias, aplicando conocimientos mediante trabajo colaborativo en diagnostico de residuos, diseno de prototipos y analisis de datos ambientales.',
metodologia:'Semillero de investigacion SISTEAM (grado 11) que identifica el tratamiento actual de residuos, disena e implementa una alternativa automatizada y evalua permanentemente los resultados obtenidos.',
tics:'FreeCAD para el diseno y modelado 2D/3D de la estructura fisica; Fritzing para el diseno electronico; tarjeta Arduino con sensores y actuadores conectados.',
aportes:'Iniciativa transversal que integra Tecnologia e Informatica con Ciencias Naturales, Mecanica Industrial, Electricidad, Electronica y Dibujo Arquitectonico en un solo prototipo funcional.' },
n5: { zona:'nac', nombre:'5. Plan Lector, el Libro Viajero y Zona Familia (Orquidea Estereo)',
img:'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800',
contexto:'Institucion Educativa San Lorenzo, con sedes rurales en Suaza, Huila. Liderada por la docente Maria Yaneth Soto Botello, busca derribar el aislamiento del aula rural convirtiendo el territorio en un ecosistema de lectura, escritura y oralidad.',
enfoque:'Sociocultural (valida saberes populares y memorias locales), humanista y de corresponsabilidad (fortalece vinculos afectivos entre hogar e institucion involucrando a familias y cuidadores).',
metodologia:'El Libro Viajero como estrategia itinerante donde cada familia se convierte en autora; Plan Lector con exploracion libre e interpretacion creativa; oralidad participativa y dialogica para la construccion de sentido.',
tics:'Radiodifusion mediante la emisora comunitaria Orquidea Estereo y su programa Zona Familia, que supera la brecha de conectividad digital en zonas rurales dispersas.',
aportes:'Articulacion transmedia comunitaria (libro, plan lector y radio); padres y cuidadores como co-disenadores del aprendizaje; fortalecimiento del tejido social rural mediante la palabra.' },
i1: { zona:'intl', nombre:'6. Peque Fotos: Descubriendo Nuestro Mundo con IA (Espana)',
img:'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800',
contexto:'CEIP Luis Costa, Murcia, con 6 aulas de Infantil y 12 de Primaria (450 ninos aprox.). Centro con programa bilingue (British Council) y fuerte implicacion del profesorado en proyectos innovadores.',
enfoque:'Pensamiento de diseno y aprendizaje basado en competencias: emprendedora, matematica y STEM, ciudadana, conciencia cultural, digital, comunicacion linguistica y aprender a aprender.',
metodologia:'Agrupamientos flexibles (individual, parejas y pequenos grupos) heterogeneos para fomentar inclusion y aprendizaje entre iguales, con oportunidades equitativas de participacion.',
tics:'IA generativa (PixVerse y DALL-E) para videos e imagenes; app Quiver para dibujos en 3D; camara 360 grados y tablet; pizarra digital; Bookcreator para el libro final.',
aportes:'Proyecto STEAM que analiza el clima y la transicion dia-noche mediante imagenes 360, usando IA para representar los aprendizajes en un libro digital accesible por codigo QR.' },
i2: { zona:'intl', nombre:'7. Robots y Emociones (Espana)',
img:'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
contexto:'Colegio San Jose de Calasanz, Olvera (Cadiz), con 290 alumnos y nivel sociocultural medio-alto. Centro con Aula del Futuro (sello INTEF) y amplia trayectoria en proyectos STEM. Protagonizado por 5 curso de Primaria (2023/24).',
enfoque:'Aprendizaje Basado en Retos, uso de Recursos Educativos Abiertos, aprender haciendo, aprendizaje cooperativo en grupos heterogeneos combinado con ejercicios multinivelados bajo el Modelo DUA.',
metodologia:'Aprendizaje experiencial, instruccion directa y reflexion cognitiva: el alumnado activa conocimientos previos, planifica hipotesis, investiga y genera producciones finales propias.',
tics:'Placa Micro:bit para explorar componentes electronicos; entorno de programacion MakeCode; Scratch para programar los robots.',
aportes:'Construccion de un pequeno robot que ayuda a identificar, expresar y controlar las emociones, fortaleciendo el bienestar propio y la relacion con los demas.' },
i3: { zona:'intl', nombre:'8. Future Teacher Kit (Ecuador)',
img:'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=800',
contexto:'Estrategia de formacion docente implementada en Ecuador en 2025 mediante la articulacion entre el Ministerio de Educacion, UNESCO Quito y Santiago, UNICEF y GIZ, orientada a zonas con brechas de conectividad e infraestructura limitada.',
enfoque:'Socioconstructivista: el docente es agente de cambio y mediador reflexivo, promoviendo comunidades de practica donde los educadores comparten experiencias y resuelven problemas pedagogicos concretos.',
metodologia:'Aprendizaje situado, flexible y aplicado bajo el principio de alineacion constructiva: recepcion de insumos breves via mensajeria, colaboracion entre pares y certificacion final tras evidenciar transformaciones en la practica.',
tics:'Estrategia low-tech basada en WhatsApp y plataformas de mensajeria ampliamente conocidas, evitando depender de plataformas complejas de alta demanda tecnologica.',
aportes:'Convierte herramientas cotidianas de mensajeria en ambientes de aprendizaje profesional; ofrece un modelo escalable e inclusivo de formacion docente para contextos de baja conectividad en America Latina.' },
i4: { zona:'intl', nombre:'9. Transformacion Digital Colaborativa (Chile)',
img:'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=800',
contexto:'Politica publica impulsada por el Ministerio de Educacion de Chile junto a la UNESCO, mediante el Plan Nacional para la Transformacion Digital de la Educacion, orientada a integrar tecnologias de forma equitativa y sostenible.',
enfoque:'La tecnologia al servicio del aprendizaje, la inclusion y el desarrollo integral, con el docente como actor central del proceso, desarrollando competencias digitales vinculadas a evaluacion, diseno e inclusion.',
metodologia:'Proceso colaborativo de construccion de politica publica: revision documental, entrevistas, encuestas, grupos focales y talleres de validacion con actores del ecosistema educativo.',
tics:'Seis pilares estrategicos: coordinacion y liderazgo, capacidad y cultura, infraestructura y conectividad, costos y sostenibilidad, contenidos digitales, y datos y evidencia, incluyendo IA con criterios eticos.',
aportes:'Comprende la transformacion digital como politica educativa sistemica centrada en la equidad, articulando ciudadania digital, competencias docentes, conectividad e inteligencia artificial responsable.' },
i5: { zona:'intl', nombre:"10. World's Largest Lesson (Reino Unido)",
img:'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800',
contexto:'Iniciativa internacional creada por Project Everyone junto a UNICEF y UNESCO, que promueve el conocimiento y apropiacion de los 17 Objetivos de Desarrollo Sostenible mediante recursos gratuitos en mas de 30 idiomas.',
enfoque:'Constructivista, humanista y basado en la Educacion para el Desarrollo Sostenible, donde el estudiante es protagonista y el docente actua como facilitador, conectando contenidos con la realidad local y global.',
metodologia:'Aprendizaje Basado en Proyectos y en Problemas, aprendizaje cooperativo, experiencial y basado en la accion (Action Learning), impulsando la investigacion y ejecucion de soluciones reales.',
tics:'Recursos digitales interactivos, videos y animaciones, guias descargables, juegos educativos, materiales multimedia y actividades virtuales para el aprendizaje hibrido.',
aportes:'Integra los ODS en el curriculo escolar, promueve una ciudadania global comprometida, usa narrativas y retos internacionales, y conecta instituciones de numerosos paises en experiencias compartidas.' }
};

// Posiciones dentro de cada sala: [x, y, z, rotY, imgThumb, etiqueta corta]
const LAYOUT_NAC = {
n1: [-14.8, 2.8, -12, 90, 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=500', '1. Redes y Gamificacion'],
n2: [-14.8, 2.8, -1, 90, 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=500', '2. Mi Escuela Canta'],
n3: [-14.8, 2.8, 10, 90, 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=500', '3. Edupuntos.co'],
n4: [14.8, 2.8, -12, -90, 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=500', '4. Residuos Organicos'],
n5: [14.8, 2.8, -1, -90, 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500', '5. Libro Viajero']
};
const LAYOUT_INTL = {
i1: [-14.8, 2.8, -12, 90, 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=500', '6. Peque Fotos IA'],
i2: [-14.8, 2.8, -1, 90, 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=500', '7. Robots y Emociones'],
i3: [-14.8, 2.8, 10, 90, 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=500', '8. Future Teacher Kit'],
i4: [14.8, 2.8, -12, -90, 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=500', '9. Chile Digital'],
i5: [14.8, 2.8, -1, -90, 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=500', "10. World's Largest Lesson"]
};
