const STATIONS = {
  n1: { zona:'nac', img:'https://images.unsplash.com/photo-1568658176307-e730ceea3576?w=800',
    nombre:'1. Aulas del Siglo XXI - Computadores para Educar',
    contexto:'Escuelas públicas urbanas con brechas de equipamiento superadas en el territorio nacional.',
    enfoque:'Constructivismo social y alfabetización digital crítica.',
    metodologia:'Aprendizaje Basado en Proyectos (ABP) transdisciplinares.',
    tics:'Laboratorios virtuales, tabletas con software interactivo y kits de robótica educativa de bajo costo.',
    aportes:'Democratización del acceso tecnológico mediante contenidos regionales precargados.' },
  n2: { zona:'nac', img:'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800',
    nombre:'2. Escuela Nueva Activa - Innovación Rural',
    contexto:'Aulas multigrado en zonas rurales dispersas de difícil acceso geográfico.',
    enfoque:'Aprendizaje centrado en el estudiante, cooperativo y adaptado a ritmos individuales.',
    metodologia:'Aprendizaje Cooperativo Adaptativo con guías de autoaprendizaje.',
    tics:'Plataformas móviles de seguimiento comunitario y terminales con carga solar.',
    aportes:'Flexibilidad del calendario escolar para asimilar los ciclos agrícolas.' },
  n3: { zona:'nac', img:'https://images.unsplash.com/photo-1581092921461-eab62e97a780?w=800',
    nombre:'3. Ruta STEM+A - Tecnoacademias SENA',
    contexto:'Educación media técnica articulada con centros de desarrollo tecnológico.',
    enfoque:'Enfoque STEM+A orientado a la resolución de problemáticas del entorno real.',
    metodologia:'Aprendizaje Basado en Retos con Ingeniería de Diseño.',
    tics:'Modelado e impresión 3D, simulación de circuitos e IA para análisis de datos.',
    aportes:'Espacios de co-creación entre estudiantes e investigadores técnicos.' },
  n4: { zona:'nac', img:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
    nombre:'4. Aulas en Paz - Convivencia Digital',
    contexto:'Instituciones educativas vulnerables o afectadas por dinámicas sociales complejas.',
    enfoque:'Educación socioemocional y competencias ciudadanas críticas.',
    metodologia:'Juego de roles y debates basados en dilemas morales.',
    tics:'Videojuegos serios y foros digitales de mediación escolar.',
    aportes:'Integración de la salud mental y la empatía dentro del currículo.' },
  n5: { zona:'nac', img:'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
    nombre:'5. Territorios Creativos - Computadores para Educar Innova',
    contexto:'Instituciones educativas étnicas e interculturales de alta diversidad.',
    enfoque:'Etnoeducación activa e interculturalidad crítica.',
    metodologia:'Aprendizaje Basado en la Indagación con cartografía social.',
    tics:'Traducción de lenguas nativas, producción audiovisual y SIG.',
    aportes:'Fusión de saberes ancestrales con herramientas tecnológicas modernas.' },
  i1: { zona:'intl', img:'https://images.unsplash.com/photo-1544717305482-2782549b5136?w=800',
    nombre:'6. Modelo Fenómeno — Finlandia',
    contexto:'Sistema educativo nacional público descentralizado, enfocado en equidad social.',
    enfoque:'Aprendizaje holístico, integrado y contextualizado en la vida real.',
    metodologia:'Aprendizaje Basado en Fenómenos, sin divisiones rígidas de asignaturas.',
    tics:'Entornos virtuales de aprendizaje integrados y portafolios en la nube.',
    aportes:'Abordaje de problemáticas globales integrando varias disciplinas a la vez.' },
  i2: { zona:'intl', img:'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800',
    nombre:'7. High Tech High — San Diego, Estados Unidos',
    contexto:'Red de escuelas charter de alta diversidad, pionera en diseño curricular.',
    enfoque:'"Deeper Learning": conocimiento aplicado con propósitos reales.',
    metodologia:'Aprendizaje Basado en Proyectos con exposición pública final.',
    tics:'Software de diseño CAD y herramientas colaborativas de gestión.',
    aportes:'Defensas públicas de portafolios en lugar de exámenes estandarizados.' },
  i3: { zona:'intl', img:'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
    nombre:'8. Movimiento Maker — Tinkering Studio',
    contexto:'Espacios de aprendizaje no formal inspirados en el Exploratorium.',
    enfoque:'Construccionismo mediante el diseño y el ensayo-error.',
    metodologia:'Tinkering: pensar con las manos combinando arte y ciencia.',
    tics:'Microcontroladores de hardware libre como Arduino y Makey Makey.',
    aportes:'Reencuadre del error escolar como proceso iterativo normalizado.' },
  i4: { zona:'intl', img:'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800',
    nombre:'9. Aulas Inteligentes — Singapur',
    contexto:'Escuelas hiperconectadas bajo la política "Smart Nation".',
    enfoque:'Pensamiento computacional y metacognición con IA adaptativa.',
    metodologia:'Progresión Concreto-Pictórico-Abstracto (CPA).',
    tics:'Tutores inteligentes con IA y analíticas de aprendizaje en tiempo real.',
    aportes:'Plataformas que ajustan la dificultad por estudiante en tiempo real.' },
  i5: { zona:'intl', img:'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    nombre:'10. Red Global de Aprendizaje (NPDL) — Michael Fullan',
    contexto:'Red internacional de escuelas liderada por Michael Fullan.',
    enfoque:'Marco de las "6 Cs": Carácter, Ciudadanía, Colaboración, Comunicación, Creatividad y Pensamiento Crítico.',
    metodologia:'Aprendizaje Profundo con alianzas de impacto social.',
    tics:'Redes globales de videoconferencia y rúbricas en la nube.',
    aportes:'Evaluación sistémica del progreso educativo a nivel mundial.' }
};
